UI of Home, Sign in and Sign up completed
AliabbasMerchant/SecureNotes pull request #21
Opened 2021-03-14 06:04 UTC by rakesh-201

A few thing I would like to clear:
- The theme of the site is a point of discussion and hence I have stored all the colors used in this site in a color.js file and importing from this file to all the components, so that the theme changing is a bit easy
- All the pages are responsive
- In the App.tsx file there is a variable temporary which when set to 1 we can see the site for logedin users and when set to 0 the site for logedout users appear.
- The NotesOverview Screen isn't complete, some work is still left which I will be completing very soon.
- Also, I apologies for the delay, happened due to some genuine issue.

Some Images are attached below: 
![Home](https://user-images.githubusercontent.com/60790259/111059135-19b46100-84b9-11eb-8bf8-022273f1eaf3.png)
![Home](https://user-images.githubusercontent.com/60790259/111059136-1c16bb00-84b9-11eb-9940-372689c0e9ec.png)
![Sign Up](https://user-images.githubusercontent.com/60790259/111059138-1d47e800-84b9-11eb-8cc2-f0198a50b8fc.png)
![Overview](https://user-images.githubusercontent.com/60790259/111059139-1de07e80-84b9-11eb-939a-37873d35b53b.png)

2021-03-17 06:34 UTC, rakesh-201 commented
@AliabbasMerchant @ShubhankarKG

2021-03-19 12:27 UTC, AliabbasMerchant requested changes
1. Don't create 2 separate components for Desktop and Mobile. 1 Single component should be able to handle both. (pass a `mobile` boolean prop if-and-only-if needed)
2. Please remove the long, extra commented out stuff
3. Next time onwards, please do not make huge formatting changes in a PR that also has new/edited stuff to be reviewed. The PR size increases significantly. You can create a separate commit and then indicate that, or even better, make a separate PR itself.

2021-03-19 12:27 UTC, AliabbasMerchant commented on client/src/App.tsx
> +  const temporary = 0;
Please give better and descriptive names to variables

2021-03-21 09:00 UTC, rakesh-201 commented
All the mentioned changes are done.

2021-03-24 05:31 UTC, ShubhankarKG approved these changes

2021-03-24 05:51 UTC, merged